# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'V1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(723, 567)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        # 选择文件
        self.pushButton.setGeometry(QtCore.QRect(90, 30, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(Dialog.clickChooseFileBtn)
        # 文件夹路径
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(220, 40, 381, 31))
        self.lineEdit.setObjectName("lineEdit")
        # 切片
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 90, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(Dialog.clickCutBtn)

        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(210, 240, 361, 181))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -16, 500, 500))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(500, 500))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(500, 500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(0, 20, 341, 500))
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 110, 731, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 150, 151, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.currentIndexChanged.connect(Dialog.clickComboBox)
        # 播放原片段
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 210, 121, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(Dialog.clickPlayRaw)
        # 录制
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 260, 121, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(Dialog.clickRecord)
        # 播放录制片段
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 310, 121, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(Dialog.clickPlayRecord)
        #选择BGM
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 360, 121, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(Dialog.clickBGMBtn)
        # 文件夹路径
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 410, 121, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        #合成
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 460, 121, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(Dialog.clickSummon)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(210, 120, 371, 101))
        self.label_2.setObjectName("label_2")

        self.checkBox=QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(40, 510, 121, 41))
        self.checkBox.setObjectName("checkBox")
        self.checkBox.clicked.connect(Dialog.clickCheckBox)
        self.label_3=QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 510, 200, 41))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "选择文件"))
        self.pushButton_2.setText(_translate("Dialog", "切片"))
        self.label.setText(_translate("Dialog", "状态信息\n"))
        self.pushButton_3.setText(_translate("Dialog", "播放原片段"))
        self.pushButton_4.setText(_translate("Dialog", "录制"))
        self.pushButton_5.setText(_translate("Dialog", "播放录制片段"))
        self.pushButton_6.setText(_translate("Dialog", "选择BGM"))
        self.pushButton_7.setText(_translate("Dialog", "合成"))
        self.label_2.setText(
            _translate("Dialog", "<html><head/><body><p>原音频时间|录制时间</p><p>          |</p></body></html>"))
        self.label_3.setText("是否直接使用原片段")
